server.port=8080

#spring.datasource.url=jdbc:h2:mem:ordersdb
#spring.datasource.driver-class-name=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
#spring.sql.init.mode=always

app.environment=local

app.datasource.order.url=jdbc:h2:mem:ordersdb
app.datasource.order.driver-class-name=org.h2.Driver
app.datasource.order.username=sa
app.datasource.order.password=

spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml