server.port=8081

#spring.datasource.url=${DB_URL:jdbc:h2:mem:devdb}
#spring.datasource.username=${DB_USERNAME:sa}
#spring.datasource.password=${DB_PASSWORD:}

spring.h2.console.enabled=false
spring.sql.init.mode=never

app.environment=dev